version: "3"
services:
  lab1-cicd: # name of the service
    image: lab1-cicd # the image to use
    container_name: lab1-cicd # what to label the container for docker ps
    ports:
      - 8080:8080
    restart: unless-stopped

#  lab1-cicd:
#    build:
#      context: .
#    ports:
#      - 8080:8080
#    environment:
#      - SERVER_PORT=8080
#    volumes:
#      - ./:/app
#    command: ./mvnw spring-boot:run
#    restart: unless-stopped
#    command: ./mvnw spring-boot:run -Dspring-boot.run.profiles=heroku
#  postgres:

#    image: library/postgres:13
#    container_name: postgres
#    restart: on-failure
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: "postgres"
#      POSTGRES_DB: postgres
#    volumes:
#      - db-data:/var/lib/postgresql/data
#      - ./postgres/:/docker-entrypoint-initdb.d/
#    ports:
#      - 5432:5432
#
#volumes:
#  db-data: