name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v1
        with:
          java-version: 11

#      - name: GitHub Action for Maven (build)
#        run: mvn package -Dmaven.test.skip # TODO: add unit tests

      - name: Deploy Docker Image to Heroku App
        uses: akhileshns/heroku-deploy@v3.12.12 # syntax error removed
        with:
          heroku_api_key: 1d2d9518-5fe3-4db2-a191-88313365f768
          heroku_app_name: lab1-cicd
          heroku_email: borisovsk_a@mail.ru
          usedocker: true

#      - name: Deploy
#        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
#        with:
#          heroku_api_key: da99cb25-cfad-4898-b1d3-d457329620eb
#          heroku_app_name: "savenko-personservice"
#          heroku_email: "finistars@mail.ru"
#          usedocker: true
      - name: Run API Tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          collection: postman/[inst] Lab1.postman_collection.json
          environment: postman/[inst][heroku] Lab1.postman_environment.json
          delayRequest: 50
          reporters: cli

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: badges branch and make dir
        run: |
          git checkout badges 2>/dev/null || git checkout -b badges
          mkdir -p .github/badges

      - name: points badge
        uses: emibcn/badge-action@v1
        with:
          LABEL: 'Points'
          STATUS: ${{ steps.autograder.outputs.Points }}
          COLOR: cyan
          path: '.github/badges/points.svg'

      - name: Commit badge
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add '.github/badges/points.svg'
          git commit -m "Add/Update badge"
        continue-on-error: true

      - name: Push badge commit
        uses: ad-m/github-push-action@master
        if: success()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: badges

